routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['roles']], function(){

    Route::get('/', 'WellcomeController@wellcome')->name('wellcome');
    
    Auth::routes();
    
    Route::resource('admin','Admin\AdminController');
    Route::resource('security','Admin\SecurityController');
    Route::resource('pages','Admin\PagesController');
    Route::resource('roles','Admin\RolesController');
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('teachers','Admin\TeachersController');
    Route::resource('schedule','Admin\ScheduleController');
    Route::resource('class','Admin\ClassController');




    Route::resource('client','Client\ClientController');
    Route::resource('clientCategories','Client\CategoriesController');
    Route::resource('clientClasses','Client\ClassController');
    Route::resource('wishlist','Client\WishlistController');
    
    Route::get('/home', 'HomeController@index')->name('home');
    
});

app/WishList.php
<?php

namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;

class WishList extends Model
{
    const table = 'wishlists';
    protected $table = self::table;
    protected $primaryKey = 'id';

    protected $fillable = [
        'user_id','class_id'
    ];

    static function store($id){
        if(self::inList($id)==0){
            return parent::create([
                'user_id'=>Auth::user()->id,
                'class_id'=>$id
            ])->id;
        } else return "error";
      
    }

    static function inList($id){
        if(Auth::user()){
            $exist=parent::where('class_id',$id)->where('user_id',Auth::user()->id)->first();
            $return=$exist ? 1 : 0;
            return $return;
        } else return 0;
       
    }

    public function class(){
        return $this->belongsTo('App\ClassModel','class_id');
    }
}

app/Http/Controllers/Client/BuyController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BuyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/CategoriesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Category;
use App\WishList;
use App\ClassModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
   

    public function index(){
        $categories=Category::allPaginate(8);
        $categoriesAll=Category::all();
        return view('client.categories.index',['categories'=>$categories,'categoriesAll'=>$categoriesAll]);
    }

    public function show($id){
        $category=Category::find($id);
        $classes=Category::getClasses($id);
        $categoriesAll=Category::all();

        foreach ($classes as $i => $class) {
            $class->exist=WishList::inList($class->id);
        }

        return view('client.categories.show',['category'=>$category,'classes'=>$classes,'categoriesAll'=>$categoriesAll]);
    }
}

app/Http/Controllers/Client/ClassController.php
<?php

namespace App\Http\Controllers\Client;

use Auth;
use App\WishList;
use App\Category;
use App\ClassModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClassController extends Controller
{
    public function show($id){
        $class=ClassModel::find($id);
        $categoriesAll=Category::all();

        $class->exist=WishList::inList($id);
        return view('client.categories.classes.show',['class'=>$class,'categoriesAll'=>$categoriesAll]);
    }
}

app/Http/Controllers/Client/ClientController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/WishlistController.php
<?php

namespace App\Http\Controllers\Client;

use Auth;
use App\WishList;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class WishlistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        foreach (Auth::user()->wishlist as $wishlist) {
            Auth::user()->wishlist->exist=$wishlist->inList($wishlist->class->id);
        }
        return view('client.wishlist.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        return WishList::store($request['id']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        WishList::where('id',$id)->delete();
        return 1;
    }
}

resources/views/client/wishlist/index.blade.php
@extends('layouts.client')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <p class="h3 m-0"><i class="fas fa-heart"></i> Wishlist</p>
        </div>
    </div>
    <hr>
    <div class="row mt-2">
        @foreach(Auth::user()->wishlist as $wishlist)
   
        <?php 
            $class=$wishlist->class
        ?>
        <div class="mb-3 col-md-4">
            <div class="card card-product">
                <div class="img-wrap">
                    <a href="{{route('clientClasses.show',['id'=>$class->id])}}"><img src="{{ asset('/images/classes/'.$class->img)}}"></a>
                </div>
                <div class="m-2 info-wrap">
                    <h4 class="title">{{$class->name}}</h4>
                    <p class="desc text-truncate">{{$class->description}}</p>
                    <div class="rating-wrap">
                        <div class="label-rating">{{$class->seats}} seats</div>
                        <div class="price-wrap h5">
                            <span class="price-new">{{$class->price}} lei</span>
                        </div>
                    </div>
                </div>
                <div class="m-2 bottom-wrap">
                   
                    <div class="container">
                        <div class="row">
                            <a href="{{route('clientClasses.show',['id'=>$class->id])}}" class="btn ml-1 my-1 col-md btn-sm btn-primary">
                                <i class="fas fa-info"></i> More details
                            </a>
                            <button data-url="{{route('wishlist.destroy',['id'=>$wishlist->id])}}" class="btn-wishlist-delete btn ml-1 my-1 col-md btn-sm btn-danger">
                                <i class="fas fa-trash"></i> Delete
                            </button>
                            <a href="" class="btn ml-1 col-md my-1 btn-sm btn-success">
                                <i class="fas fa-shopping-cart"></i> Buy
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection