routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['roles']], function(){

    Route::get('/', 'WellcomeController@wellcome')->name('wellcome');
    
    Auth::routes();
    
    Route::resource('admin','Admin\AdminController');
    Route::resource('security','Admin\SecurityController');
    Route::resource('pages','Admin\PagesController');
    Route::resource('roles','Admin\RolesController');
    Route::resource('categories','Admin\CategoriesController');
    Route::resource('teachers','Admin\TeachersController');
    Route::resource('schedule','Admin\ScheduleController');
    Route::resource('class','Admin\ClassController');




    Route::resource('client','Client\ClientController');
    Route::resource('clientCategories','Client\CategoriesController');
    Route::resource('clientClasses','Client\ClassController');
    Route::resource('wishlist','Client\WishlistController');
    
    Route::get('/home', 'HomeController@index')->name('home');
    
});

app/Category.php
<?php

namespace App;

use Auth;
use App\ClassModel;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    const table = 'categories';
    protected $table = self::table;
    protected $primaryKey = 'id';

    protected $fillable = [
        'name','description','img','user_id'
    ];

    static function store($name,$description){
        return parent::create([
            'user_id'=>Auth::user()->id,
            'name'=>$name,
            'description'=>$description,
        ])->id;
    }

    static function setImg($id,$img){
        parent::where('id',$id)->update([
            'img'=>$img
        ]);

        return 1; 
    }

    static function allPaginate($nr){
        return parent::where('visibility',1)->paginate($nr);
    }

    static function getClasses($id){
        return ClassModel::where('cat_id',$id)->where('visibility',1)->paginate(6);
    }

    static function destroy($id){
        parent::where('id',$id)->update([
            'visibility'=>0
        ]);
        return 1;
    }
    
    public function classes(){
        return $this->hasMany('App\ClassModel',"cat_id");
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Teachers;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $categories=Category::allPaginate(8);
        return view('admin.categories.index',['categories'=>$categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'category-img' => ['required', 'image', 'max:2048']
        ]);

        if ($validator->passes()) {
            $id=Category::store($request['name'],$request['description']);
            $image = $request->file('category-img');
            $new_name = 'category-'.$id.'.'. $image->getClientOriginalExtension();
            $image->move('./images/categories', $new_name);
            Category::setImg($id,$new_name);
            return 1;
        }else{
            return response()->json([
                'errors' => $validator->errors()->all()
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $classes=Category::find($id)->classes()->where('visibility',1)->paginate(6);
       $category=Category::find($id);
       $teachers=Teachers::getTeachers();
       return view('admin.categories.show',['category'=>$category,'teachers'=>$teachers,'classes'=>$classes]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category=Category::find($id);
        return $category;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Category::where('id',$id)->update([
            'name'=>$request['name'],
            'description'=>$request['description']
            ]);
        return $id;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return Category::destroy($id);
    }
}

app/Http/Controllers/Client/BuyController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BuyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/CategoriesController.php
<?php

namespace App\Http\Controllers\Client;

use App\Category;
use App\WishList;
use App\ClassModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
   

    public function index(){
        $categories=Category::allPaginate(8);
        $categoriesAll=Category::all();
        return view('client.categories.index',['categories'=>$categories,'categoriesAll'=>$categoriesAll]);
    }

    public function show($id){
        $category=Category::find($id);
        $classes=Category::getClasses($id);
        $categoriesAll=Category::all();

        foreach ($classes as $i => $class) {
            $class->exist=WishList::inList($class->id);
        }

        return view('client.categories.show',['category'=>$category,'classes'=>$classes,'categoriesAll'=>$categoriesAll]);
    }
}

app/Http/Controllers/Client/ClassController.php
<?php

namespace App\Http\Controllers\Client;

use Auth;
use App\WishList;
use App\Category;
use App\ClassModel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClassController extends Controller
{
    public function show($id){
        $class=ClassModel::find($id);
        $categoriesAll=Category::all();

        $class->exist=WishList::inList($id);
        return view('client.categories.classes.show',['class'=>$class,'categoriesAll'=>$categoriesAll]);
    }
}

app/Http/Controllers/Client/ClientController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Client/WishlistController.php
<?php

namespace App\Http\Controllers\Client;

use Auth;
use App\WishList;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class WishlistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        foreach (Auth::user()->wishlist as $wishlist) {
            Auth::user()->wishlist->exist=$wishlist->inList($wishlist->class->id);
        }
        return view('client.wishlist.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        return WishList::store($request['id']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        WishList::where('id',$id)->delete();
        return 1;
    }
}

resources/views/client/categories/index.blade.php
@extends('layouts.guest')

@section('content')
<div class="vh-100 mt-5 pt-5 container">
    <div class="row">
        <div class="col-md-5">
            <p class="h3"><i class="fas fa-folder"></i> Categories</p>
        </div>
    </div>
    <hr>
    <div class="row" id="categories">
        @foreach($categories->reverse() as $category)
        <div class="mb-2 col-md-3">
            <div class="card">
                <a href="{{route('clientCategories.show',['id'=>$category->id])}}"><img class="category-card-img card-img-top" src="{{ asset('/images/categories/'.$category->img)}}" alt="Card image cap"></a>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-10">
                            <a href="{{route('clientCategories.show',['id'=>$category->id])}}"> 
                                <h4 data-id="{{$category->id}}" class="category-title card-title">{{$category->name}}</h4>
                            </a>
                        </div>
                    </div>
                   
                    <div class="row">
                        <div class="col-md-10 ">
                            <a href="{{route('clientCategories.show',['id'=>$category->id])}}">      
                                <p data-id="{{$category->id}}" class="category-description text-truncate card-text">{{$category->description}}</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
    <div class="my-3 row">
        <div class="col-md-4">
            {{ $categories->onEachSide(0)->links() }}
        </div>
    </div>
</div>

@endsection

resources/views/client/categories/show.blade.php
@extends('layouts.guest')

@section('content')
<div class="vh-100 mt-5 pt-5 container">
    <div class="row">
        <div class="col-md-10">
            <p class="h3">{{$category->name}}</p>
            <p>{{$category->description}}</p>
        </div>
       
    </div>
    <hr>
    
    <div id="classes-list" class="row">
        @foreach ($classes as $class)
        <div class="mb-3 col-md-4">
            <div class="card card-product">
                <div class="img-wrap">
                    <a href="{{route('clientClasses.show',['id'=>$class->id])}}"><img src="{{ asset('/images/classes/'.$class->img)}}"></a>
                </div>
                <div class="m-2 info-wrap">
                    <h4 class="title">{{$class->name}}</h4>
                    <p class="desc text-truncate">{{$class->description}}</p>
                    <div class="rating-wrap">
                        <div class="label-rating">{{$class->seats}} seats</div>
                    </div>
                    <div class="price-wrap h5">
                        <span class="price-new">{{$class->price}} lei</span>
                    </div>
                </div>
                <div class="m-2 bottom-wrap">
                    <div class="container">
                        <div class="row">
                            @if($class->exist==0)    
                                <button data-auth="{{Auth::user()? 1 : 0}}" data-id="{{$class->id}}" data-url="{{route('wishlist.store')}}" id="add-class-wishlist" class="btn ml-1 my-1 col-md btn-sm btn-danger">
                                    <i class="fas fa-heart"></i> Wishlist
                                </button>
                            @endif
                            <a href="{{route('clientClasses.show',['id'=>$class->id])}}"
                                class="btn ml-1 my-1 col-md btn-sm btn-primary">
                                <i class="fas fa-info"></i> More details
                            </a>
                            <a href="" class="btn ml-1 col-md my-1 btn-sm btn-success">
                                <i class="fas fa-shopping-cart"></i> Buy
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </div>
    <div class="row my-3">
        <div class="col-md-4">
            {{ $classes->onEachSide(0)->links() }}
        </div>
    </div>
</div>


@endsection